# Generated by Django 5.0.6 on 2024-07-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.CharField(max_length=100)),
            ],
        ),
    ]
