# Generated by Django 5.0.6 on 2024-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0005_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumidor', models.CharField(max_length=100)),
            ],
        ),
    ]
