# Generated by Django 5.0.6 on 2024-08-13 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0006_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock_a', models.IntegerField(verbose_name='Stock Actual')),
                ('stock_r', models.IntegerField(verbose_name='Stock Reposicion')),
                ('stock_m', models.IntegerField(verbose_name='Stock Minimo')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.categoria')),
                ('edad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.edad')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.marca')),
            ],
        ),
    ]
