# Generated by Django 5.0.6 on 2024-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0007_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='obs',
            field=models.CharField(default='', max_length=150, verbose_name='Observaciones'),
        ),
    ]
