# Generated by Django 5.0.6 on 2024-08-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0009_remove_producto_categoria_remove_producto_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='edad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.edad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.marca'),
        ),
    ]
