# Generated by Django 5.1 on 2024-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0011_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hs_cier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre'),
        ),
    ]
