# Generated by Django 5.1 on 2024-08-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0012_alter_caja_fecha_hs_cier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_r',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Reposicion'),
        ),
    ]
