# Generated by Django 5.1 on 2024-08-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0014_animal_consistencia_tamaño_producto_des_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nombre',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='nombre',
            new_name='marca',
        ),
    ]
