# Generated by Django 5.1.1 on 2024-09-04 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0015_rename_nombre_animal_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=False, verbose_name='Caja Abierta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hs_cier',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha y hora de cierre'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_egr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Egresos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_ing',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ingresos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('hora_venta', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Venta')),
                ('total_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.caja')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Total unidades')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('descuento', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%')], default=0, verbose_name='Descuento')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.producto')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.venta')),
            ],
        ),
    ]
